# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: Your Site Title # Change to your desired site title
tagline: "Your tagline" # Change to your desired tagline
description: "Your site description." # Change to your description
url: https://Ki-D-Talbot.github.io
baseurl: ""

author:
  name: "Ki Talbot" # Change to your name
  url: https://github.com/Ki-D-Talbot # Change to your GitHub profile

paginate: 5

# Custom vars
version: 1.0.0

github:
  repo: https://github.com/Ki-D-Talbot/Ki-D-Talbot.github.io # Change to your actual repository

