# Site settings
title: Ki's Website
description: Personal portfolio and project site
baseurl: ""
url: "https://Ki-D-Talbot.github.io"

# Author details
author:
  name: Ki Talbot
  email: kidtalbot@gmail.com

# Social media links
social:
  twitter: https://twitter.com/yourusername
  facebook: https://facebook.com/yourusername
  github: https://github.com/Ki-D-Talbot
  email: kidtalbot@gmail.com

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git

# Theme settings
tagline: Not a Hyperspace Engineer

# Collections for your 3D models
collections:
  models:
    output: true
    permalink: /models/:path/
