# Site settings
title: Your Site Title
tagline: 'Your site tagline'
description: 'A brief description of your site'
url: https://ki-d-talbot.github.io
baseurl: ''
permalink: pretty

# Build settings
markdown: kramdown
highlighter: rouge

# Author info
author:
  name: 'Your Name'
  url: https://github.com/Ki-D-Talbot

# Sidebar nav items
github:
  repo: https://github.com/Ki-D-Talbot/Ki-D-Talbot.github.io
